[package]
edition = "2021"
name = "rust-jobscheduler"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

serde = {version = "1.0.136", features = ["derive"]}
uuid = "0.8.2"
